#!/bin/bash

connect_text="Element Desktop requires access to the password-manager-service interface

To connect the interface, in a terminal run:

sudo snap connect element-desktop:password-manager-service"
if ! snapctl is-connected password-manager-service; then
  echo "password-manager-service not connected, please connect with:"
  echo "sudo snap connect element-desktop:password-manager-service"
  zenity --title "Element Desktop: Connect to Password Manager Service" --info --text "$connect_text" --width 600
  exit
fi

if [[ ! "$XDG_CURRENT_DESKTOP" =~ .*GNOME.* ]] then
  WAYLAND_OPTS="--enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto"
fi

exec "$SNAP/opt/Element/element-desktop" --no-sandbox --disable-seccomp-filter-sandbox $WAYLAND_OPTS "$@"
