name: element-desktop
base: core22
version: 1.11.36
adopt-info: element-desktop
summary: Element Desktop
description: |
   A feature-rich client for Matrix.org

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  libraries:
    plugin: nil
    stage-packages:
      - libxss1
      - libvips42
      - libsqlcipher0
    prime:
      - usr/lib/*/libXss*
      - usr/lib/*/libvips*
      - usr/lib/*/libsqlcipher*
      - usr/lib/*/libIlm* #needed by libvips
      - usr/lib/*/libMagick* #needed by libvips
      - usr/lib/*/libcfitsio* #needed by libvips
      - usr/lib/*/libcgif* #needed by libvips
      - usr/lib/*/libexif* #needed by libvips
      - usr/lib/*/libfftw3* #needed by libvips
      - usr/lib/*/libgsf* #needed by libvips
      - usr/lib/*/libheif* #needed by libvips
      - usr/lib/*/libaec* #needed by libvips
      - usr/lib/*/libimagequant* #needed by libvips
      - usr/lib/*/libmatio* #needed by libvips
      - usr/lib/*/libopenslide* #needed by libvips
      - usr/lib/*/libwebpmux* #needed by libvips
      - usr/lib/*/libHalf* #needed by libIlmImf
      - usr/lib/*/libIex* #needed by libIlmImf
      - usr/lib/*/libIm* #needed by libIlmImf
      - usr/lib/*/liblqr* #needed by libMagickCore-6
      - usr/lib/*/libaom* #needed by libheif
      - usr/lib/*/libda* #needed by libheif
      - usr/lib/*/libde* #needed by libheif
      - usr/lib/*/libx265* #needed by libheif
      - usr/lib/*/libnuma* #needed by libheif
      - usr/lib/*/libhdf5* #needed by libmatio
      - usr/lib/*/libsz* #needed by libhdf5

  element-desktop:
    plugin: dump
    source: https://packages.element.io/debian/pool/main/e/element-desktop/element-desktop_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    build-packages:
      - gcc
      - wget
      - jq
      - dpkg
      - git
    override-pull: |
      craftctl default
      sed -i 's|Icon=element-desktop|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/element-desktop.png|' $SNAPCRAFT_PART_SRC/usr/share/applications/element-desktop.desktop
    prime:
      - opt/Element
      - usr/share/icons/hicolor/512x512/apps/element-desktop.png
      - usr/share/applications
      - -opt/*/chrome-sandbox
      - -opt/*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -opt/*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  cleanup:
    after: [ element-desktop ]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
        set -eux
        cd /snap/gnome-42-2204/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  element-desktop:
    extensions: [gnome]
    desktop: usr/share/applications/element-desktop.desktop
    command: launcher
    plugs:
      - shmem
      - camera
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - process-control
      - unity7
    environment:
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
