name: element-desktop
title: Element Desktop
base: core24
version: 1.12.9
adopt-info: element-desktop
summary: A feature-rich client for Matrix.org
description: |
  A sovereign and secure communications
  platform. Built by the creators of Matrix.

website: https://element.io/
issues: https://github.com/kenvandine/element-desktop/issues
source-code:
  - https://github.com/kenvandine/element-desktop
  - https://github.com/element-hq/element-desktop
contact: ken@vandine.org
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  nss_patch:
    plugin: nil
    source: src
    override-build: |
      gcc -shared -fPIC -o $CRAFT_PART_INSTALL/nss_patch.so nss_patch.c -ldl

  element-desktop:
    plugin: dump
    source: https://packages.element.io/debian/pool/main/e/element-desktop/element-desktop_$SNAPCRAFT_PROJECT_VERSION_$CRAFT_ARCH_BUILD_FOR.deb 
    override-pull: |
      craftctl default
      sed -i 's|Icon=element-desktop|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/element-desktop.png|' $CRAFT_PART_SRC/usr/share/applications/element-desktop.desktop
    prime:
      - opt/Element
      - usr/share/icons/hicolor/512x512/apps/element-desktop.png
      - usr/share/applications
      - -opt/*/chrome-sandbox
      - -opt/*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -opt/*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  # Needed for setting the proper desktop file name in the electron apps
  patch-desktop-file-name:
    after: [element-desktop]
    source: https://github.com/snapcrafters/patch-desktop-file-name.git
    source-subdir: electron
    plugin: nil
    override-build: |
      pip install asarPy --break-system-packages
      python3 $CRAFT_PART_SRC_WORK/patch-desktop-filename.py $CRAFT_STAGE/opt/Element/resources/app.asar
  zenity:
    plugin: nil
    stage-packages:
      - zenity
    prime:
      - usr/bin/zenity

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  element-desktop:
    extensions: [gnome]
    desktop: usr/share/applications/element-desktop.desktop
    command: launcher
    autostart: element-desktop.desktop
    plugs:
      - shmem
      - camera
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - screen-inhibit-control
      - process-control
      - unity7
      - password-manager-service
    environment:
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
      LIBSECRET_LOCAL_STORAGE: 1
