name: element-desktop
base: core20
adopt-info: element-desktop
summary: Element Desktop
description: |
   A feature-rich client for Matrix.org

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

parts:
  element-desktop:
    plugin: nil
    build-packages:
      - gcc
      - wget
      - jq
      - dpkg
      - git
    stage-packages:
      - libxss1
      - libnspr4
      - libnss3
      - libvips42
    override-build: |
      set -xeu
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/vector-im/element-desktop/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | grep -v beta | head -n 1 | cut -d'"' -f4 | tr -d 'v')
      DEB_URL="https://packages.element.io/debian/pool/main/e/element-desktop/element-desktop_"$VERSION"_amd64.deb"
      wget --quiet $DEB_URL -O element-desktop.deb
      dpkg-deb -x element-desktop.deb $SNAPCRAFT_PART_INSTALL/
      rm element-desktop.deb releases.json
      sed -i 's|Icon=element-desktop|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/element-desktop.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/element-desktop.desktop
      snapcraftctl set-version "$VERSION"
    prime:
      - -opt/*/chrome-sandbox
      - -opt/*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -opt/*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  cleanup:
    after: [ element-desktop ]
    plugin: nil
    build-snaps: [ gnome-3-38-2004 ]
    override-prime: |
        set -eux
        cd /snap/gnome-3-38-2004/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
        for CRUFT in bug lintian man; do
          rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
        done
        find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete

apps:
  element-desktop:
    extensions: [gnome-3-38]
    desktop: usr/share/applications/element-desktop.desktop
    command: opt/Element/element-desktop --use-tray-icon --no-sandbox
    plugs:
      - browser-support
      - camera
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
    environment:
      DISABLE_WAYLAND: '1'
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
      WAYLAND_DISPLAY: no-display
